export enum BodyParts {
  LEFT_HAND,
  RIGHT_HAND,
  LEFT_WRIST,
  RIGHT_WRIST,
  LEFT_ELBOW,
  RIGHT_ELBOW,
  LEFT_UNDER_SHOULDER,
  RIGHT_UNDER_SHOULDER,
  LEFT_OUTER_SHOULDER,
  RIGHT_OUTER_SHOULDER,
  LEFT_INNER_SHOULDER,
  RIGHT_INNER_SHOULDER,
  NECK_VERTICAL,
  NECK_HORIZONTAL
}
